# Generated by Django 3.1.3 on 2020-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201128_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('A', 'Receive'), ('B', 'Accepted'), ('C', 'Ready'), ('F', 'Canceled')], max_length=1),
        ),
    ]
