# Generated by Django 3.1.3 on 2020-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20201128_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_modifed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last modifed'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(default=123, max_length=255, verbose_name='PayPal payerID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=123, max_length=255, verbose_name='PayPal paymentID'),
            preserve_default=False,
        ),
    ]
