# Generated by Django 3.1.3 on 2020-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20201129_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site. Mine', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Received'), ('B', 'Accepted'), ('C', 'Ready'), ('F', 'Canceled')], max_length=1),
        ),
    ]
