# Generated by Django 3.1.3 on 2020-12-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20201208_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_restaurant_staff',
            field=models.BooleanField(default=False, help_text='Restaurant Staff', verbose_name='Restaurant Staff'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site. default', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site. manager', verbose_name='manager status'),
        ),
    ]
