# Generated by Django 3.1.3 on 2020-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menu_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site. Mine', verbose_name='staff status'),
        ),
    ]
